"""Lump-type identifier table.

Auto-generated by ``tools/gen_lump_types.py`` from ``lump_types.h`` of the
MIT-licensed ``ripped_apart`` project (https://github.com/chaoticgd/ripped_apart).
Do not edit by hand.

Provenance, in two parts:

* ``LUMP_TYPES`` (78 entries) is parsed verbatim from that header.
* ``LUMP_LANGUAGE_KNOWN`` (9 entries) is **not** in the upstream header.
  Those are the localisation string-table lump CRCs, recovered by
  inspecting the game files.  The generator hardcodes them, so
  regenerating does not and cannot re-derive them from ripped_apart.

See docs/SOURCES.md for the full breakdown of what came from where.
"""

from __future__ import annotations

#: Maps the u32 lump-type CRC stored in ``1TAD`` container headers to a
#: human-readable name.  Unknown CRCs are simply absent.
LUMP_TYPES: dict[int, str] = {
    0x00823787: 'Model Texture Overrides',        # MODEL_TEXTURE_OVERRIDES
    0x06abcab2: 'Zone Scene Objects',             # ZONE_SCENE_OBJECTS
    0x06eb7efc: 'Model Look',                     # MODEL_LOOK
    0x0859863d: 'Model Index',                    # MODEL_INDEX
    0x09dc30ab: 'Anim Clip Curves',               # ANIM_CLIP_CURVES
    0x0cf58a6e: 'Zone Actor Groups',              # ZONE_ACTOR_GROUPS
    0x135832c8: 'Actor Prius Built',              # ACTOR_PRIUS_BUILT
    0x15df9d3b: 'Model Joint',                    # MODEL_JOINT
    0x2236c47a: 'Level Link Names',               # LEVEL_LINK_NAMES
    0x27ca5246: 'Model Splines',                  # MODEL_SPLINES
    0x283d0383: 'Model Built',                    # MODEL_BUILT
    0x2ba33702: 'Level Zone Names',               # LEVEL_ZONE_NAMES
    0x2f4056ce: 'Conduit Asset Refs',             # CONDUIT_ASSET_REFS
    0x30dada09: 'Zone Asset References',          # ZONE_ASSET_REFERENCES
    0x3250bb80: 'Model Material',                 # MODEL_MATERIAL
    0x32fac8e0: 'Actor Built',                    # ACTOR_BUILT
    0x364a6c7c: 'Actor Object Built',             # ACTOR_OBJECT_BUILT
    0x36a6c8cc: 'Archive TOC Texture Asset Ids',  # ARCHIVE_TOC_TEXTURE_ASSET_IDS
    0x396f9418: 'Level Regions Built',            # LEVEL_REGIONS_BUILT
    0x3976e44c: 'Anim Clip Path',                 # ANIM_CLIP_PATH
    0x398abff0: 'Archive TOC File Metadata',      # ARCHIVE_TOC_FILE_METADATA
    0x3ab204b9: 'Actor Asset Refs',               # ACTOR_ASSET_REFS
    0x3c9dabdf: 'Model Spline Subsets',           # MODEL_SPLINE_SUBSETS
    0x4130d903: 'Level Region Names',             # LEVEL_REGION_NAMES
    0x4a128222: 'Config Type',                    # CONFIG_TYPE
    0x4ccea4ad: 'Model Look Group',               # MODEL_LOOK_GROUP
    0x4e023760: 'Level Zones Built',              # LEVEL_ZONES_BUILT
    0x4ede3593: 'Texture Header',                 # TEXTURE_HEADER
    0x506d7b8a: 'Archive TOC Asset IDs',          # ARCHIVE_TOC_ASSET_IDS
    0x58b8558a: 'Config Asset Refs',              # CONFIG_ASSET_REFS
    0x5cba9de9: 'Model Col Vert',                 # MODEL_COL_VERT
    0x5e54accf: 'Zone Script Actions',            # ZONE_SCRIPT_ACTIONS
    0x62297090: 'Archive TOC Texture Header',     # ARCHIVE_TOC_TEXTURE_HEADER
    0x654bded9: 'Archive TOC Asset Header Data',  # ARCHIVE_TOC_ASSET_HEADER_DATA
    0x657512bb: 'Zone Decal Geometry',            # ZONE_DECAL_GEOMETRY
    0x65bcf461: 'Archive TOC Asset Metadata',     # ARCHIVE_TOC_ASSET_METADATA
    0x6987f172: 'Zone Model Insts',               # ZONE_MODEL_INSTS
    0x70682cb8: 'Zone Actors',                    # ZONE_ACTORS
    0x731cbc2e: 'Model Locator Lookup',           # MODEL_LOCATOR_LOOKUP
    0x78d9cbde: 'Model Subset',                   # MODEL_SUBSET
    0x7a0266bc: 'Asset Types',                    # ASSET_TYPES
    0x7ca7267d: 'Level Built',                    # LEVEL_BUILT
    0x811902d7: 'Model Look Built',               # MODEL_LOOK_BUILT
    0x91de11d9: 'Zone Decal Assets',              # ZONE_DECAL_ASSETS
    0x933c0d32: 'Asset Ids',                      # ASSET_IDS
    0x97ff6eb5: 'Zone Lights',                    # ZONE_LIGHTS
    0x9df23f77: 'Anim Clip Built',                # ANIM_CLIP_BUILT
    0x9f614fab: 'Model Locator',                  # MODEL_LOCATOR
    0x9fd19c20: 'Anim Clip Data',                 # ANIM_CLIP_DATA
    0xa98be69b: 'Model Std Vert',                 # MODEL_STD_VERT
    0xb6a0b72a: 'Zone Atmosphere Name',           # ZONE_ATMOSPHERE_NAME
    0xb7380e8c: 'Model Leaf Ids',                 # MODEL_LEAF_IDS
    0xb79cf1d7: 'Anim Clip Lookup',               # ANIM_CLIP_LOOKUP
    0xbc91d1cc: 'Dependency Links',               # DEPENDENCY_LINKS
    0xbce86b01: 'Model Render Overrides',         # MODEL_RENDER_OVERRIDES
    0xbcf43558: 'Zone Decals',                    # ZONE_DECALS
    0xbdab2b0d: 'Zone Volumes',                   # ZONE_VOLUMES
    0xbeab52e7: 'Zone Script Plugs',              # ZONE_SCRIPT_PLUGS
    0xbfec699f: 'DAG_UNKNOWN',                    # DAG_UNKNOWN
    0xc5354b60: 'Model Mirror Ids',               # MODEL_MIRROR_IDS
    0xc61b1ff5: 'Model Skin Batch',               # MODEL_SKIN_BATCH
    0xc6a5905e: 'Zone Model Names',               # ZONE_MODEL_NAMES
    0xc9fb9dda: 'Archive TOC Texture Meta',       # ARCHIVE_TOC_TEXTURE_META
    0xcb8d34f9: 'Zone Impostors Atlas',           # ZONE_IMPOSTORS_ATLAS
    0xceb30e68: 'Conduit Built',                  # CONDUIT_BUILT
    0xd101a6cc: 'Asset Names',                    # ASSET_NAMES
    0xd86a7934: 'Zone Script Vars',               # ZONE_SCRIPT_VARS
    0xdc311fc3: 'Zone Impostors',                 # ZONE_IMPOSTORS
    0xdc625b3d: 'Zone Actor Names',               # ZONE_ACTOR_NAMES
    0xdca379a2: 'Model Skin Data',                # MODEL_SKIN_DATA
    0xdcc88a19: 'Model Bind Pose',                # MODEL_BIND_POSE
    0xe4158ac3: 'Zone Material Overrides',        # ZONE_MATERIAL_OVERRIDES
    0xe501186f: 'Config Built',                   # CONFIG_BUILT
    0xede8ada9: 'Archive TOC Header',             # ARCHIVE_TOC_HEADER
    0xee31971c: 'Model Joint Lookup',             # MODEL_JOINT_LOOKUP
    0xef8637d5: 'Zone Script Strings',            # ZONE_SCRIPT_STRINGS
    0xefd92e68: 'Model Physics Data',             # MODEL_PHYSICS_DATA
    0xf958372e: 'Dependency Links Heads',         # DEPENDENCY_LINKS_HEADS
}

#: Reverse lookup: human-readable name -> CRC.
LUMP_CRC: dict[str, int] = {v: k for k, v in LUMP_TYPES.items()}

# -- localisation string table ---------------------------------------------
# These nine CRCs are NOT in the upstream lump_types.h -- they were
# recovered by inspecting the containers inside d/localization.  The names
# below are descriptive, not upstream's.
LUMP_LANG_KEYS      = 0x4d73cebd  # NUL-separated key blob
LUMP_LANG_VALUES    = 0x70a382b8  # NUL-separated localised string blob
LUMP_LANG_COUNT     = 0xd540a903  # u32 string count (N)
LUMP_LANG_VALUE_OFF = 0xf80deeb4  # u32[N] offsets into the value blob (0 = untranslated)
LUMP_LANG_KEY_OFF   = 0xa4ea55b2  # u32[N] offsets into the key blob
LUMP_LANG_ZERO      = 0xb0653243  # u8[N] flag byte per entry, then 3N zeros
LUMP_LANG_KEY_HASH  = 0x06a58050  # u32[N] key hash table
LUMP_LANG_KEY_ALT   = 0xc43731b5  # u32[N] the same hashes, ascending
LUMP_LANG_HASH_OVF  = 0x0cd2cfe9  # u16[N] entry indexes, in hash order

LUMP_LANGUAGE_KNOWN: dict[int, str] = {
    0x4d73cebd: 'Language Keys',          
    0x70a382b8: 'Language Values',        
    0xd540a903: 'Language Count',         
    0xf80deeb4: 'Language Value Offsets', 
    0xa4ea55b2: 'Language Key Offsets',   
    0xb0653243: 'Language Flags',         
    0x06a58050: 'Language Key Hash',      
    0x0cd2cfe9: 'Language Sorted Indexes',
    0xc43731b5: 'Language Sorted Hashes',  
}

# -- table of contents ------------------------------------------------
LUMP_TOC_HEADER                 = 0xede8ada9  # u32 pairs (first_index, count)
LUMP_TOC_ARCHIVE_ASSET_IDS      = 0x506d7b8a  # u64[N] asset path hashes
LUMP_TOC_ARCHIVE_ASSET_METADATA = 0x65bcf461  # 16*N (size, archive, offset, header)
LUMP_TOC_FILE_METADATA          = 0x398abff0  # 0x42*A NUL-terminated archive names
LUMP_TOC_ASSET_HEADER_DATA      = 0x654bded9  # optional per-asset headers
