#!/usr/bin/env python3
"""Generate rcextract/lump_types.py from ripped_apart's lump_types.h."""
import io, os, sys

HDR = sys.argv[1] if len(sys.argv) > 1 else \
    "/tmp/opencode/ripped_apart/libra/lump_types.h"
OUT = sys.argv[2] if len(sys.argv) > 2 else "rcextract/lump_types.py"

rows = []
for line in open(HDR, encoding="utf-8", errors="replace"):
    line = line.strip()
    if not line.startswith("LUMP_TYPE("):
        continue
    parts = line[len("LUMP_TYPE("):-1].split(", ", 2)
    if len(parts) != 3:
        continue
    ident, crc, name = parts
    rows.append((int(crc, 16), ident.strip(), name.strip().strip('"')))

if not rows:
    sys.exit("no LUMP_TYPE() rows parsed from %s" % HDR)

namew = max(len(repr(n)) for _, _, n in rows)
idw = max(len(i) for _, i, _ in rows)

buf = io.StringIO()
buf.write('"""Lump-type identifier table.\n\n')
buf.write("Auto-generated by ``tools/gen_lump_types.py`` from ``lump_types.h`` of the\n")
buf.write("MIT-licensed ``ripped_apart`` project (https://github.com/chaoticgd/ripped_apart).\n")
buf.write("Do not edit by hand.\n")
buf.write('"""\n\nfrom __future__ import annotations\n\n')
buf.write("#: Maps the u32 lump-type CRC stored in ``1TAD`` container headers to a\n")
buf.write("#: human-readable name.  Unknown CRCs are simply absent.\n")
buf.write("LUMP_TYPES: dict[int, str] = {\n")
for crc, ident, name in sorted(rows):
    buf.write("    0x%08x: %-*s  # %s\n" % (crc, namew + 1, repr(name) + ",", ident))
buf.write("}\n\n")
buf.write("#: Reverse lookup: human-readable name -> CRC.\n")
buf.write("LUMP_CRC: dict[str, int] = {v: k for k, v in LUMP_TYPES.items()}\n\n")
buf.write("# -- localisation string table ---------------------------------------------\n")
buf.write("# These nine CRCs are NOT in the upstream lump_types.h -- they were\n")
buf.write("# recovered by inspecting the containers inside d/localization.  The names\n")
buf.write("# below are descriptive, not upstream's.\n")
buf.write("LUMP_LANG_KEYS      = 0x4d73cebd  # NUL-separated key blob\n")
buf.write("LUMP_LANG_VALUES    = 0x70a382b8  # NUL-separated localised string blob\n")
buf.write("LUMP_LANG_COUNT     = 0xd540a903  # u32 string count (N)\n")
buf.write("LUMP_LANG_VALUE_OFF = 0xf80deeb4  # u32[N] offsets into the value blob (0 = untranslated)\n")
buf.write("LUMP_LANG_KEY_OFF   = 0xa4ea55b2  # u32[N] offsets into the key blob\n")
buf.write("LUMP_LANG_ZERO      = 0xb0653243  # u32[N], all zero in every shipped language\n")
buf.write("LUMP_LANG_KEY_HASH  = 0x06a58050  # u32[N] key hash table\n")
buf.write("LUMP_LANG_HASH_OVF  = 0x0cd2cfe9  # u32[N/2] hash overflow table\n")
buf.write("LUMP_LANG_KEY_ALT   = 0xc43731b5  # u32[N] secondary key offsets\n")
buf.write("\n")
buf.write("LUMP_LANGUAGE_KNOWN: dict[int, str] = {\n")
for c, n in ((0x4d73cebd, "Language Keys"), (0x70a382b8, "Language Values"),
             (0xd540a903, "Language Count"), (0xf80deeb4, "Language Value Offsets"),
             (0xa4ea55b2, "Language Key Offsets"), (0xb0653243, "Language Zero"),
             (0x06a58050, "Language Key Hash"), (0x0cd2cfe9, "Language Hash Overflow"),
             (0xc43731b5, "Language Key Alt")):
    buf.write("    0x%08x: %-26s\n" % (c, repr(n) + ","))
buf.write("}\n\n")
buf.write("# -- table of contents ------------------------------------------------\n")
buf.write("LUMP_TOC_HEADER                 = 0xede8ada9  # u32 pairs (first_index, count)\n")
buf.write("LUMP_TOC_ARCHIVE_ASSET_IDS      = 0x506d7b8a  # u64[N] asset path hashes\n")
buf.write("LUMP_TOC_ARCHIVE_ASSET_METADATA = 0x65bcf461  # 16*N (size, archive, offset, header)\n")
buf.write("LUMP_TOC_FILE_METADATA          = 0x398abff0  # 0x42*A NUL-terminated archive names\n")
buf.write("LUMP_TOC_ASSET_HEADER_DATA      = 0x654bded9  # optional per-asset headers\n")

os.makedirs(os.path.dirname(OUT) or ".", exist_ok=True)
open(OUT, "w", encoding="utf-8").write(buf.getvalue())
print("wrote %s (%d lump types)" % (OUT, len(rows)))
